### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kohend**

### CODE REVIEW

**Comment by amitfin** [comment]
> It requires the Shapely module that is not required by HA itself, so you may need to install it.

I don't think that Shapely needs to be installed manually. It's part of the manifest ([here](https://github.com/amitfin/oref_alert/blob/9eb5afbfbcf25ab2acd21f7c40a0f12c2c6d7f3f/custom_components/oref_alert/manifest.json#L13)) and therefore HA installs it automatically.

**Comment by kohend** [comment]
When installing through HACS, not when adding the component manually.

**Comment by amitfin** [comment]
I don't think it matters. In both cases the dependencies get installed.

**Comment by kohend** [comment]
From what I saw in my setup, it didn't install them

**Comment by amitfin** [comment]
The conclusion is that it happened because it's a venv environment which doesn't supporting installing `requirements`. Since this is an environment generic behavior, there is no reason to add a comment about it for every custom integration that is out there.
Closing the PR.

**Pull request closed without merging**
